export const routes = {
  landing: '/',
  about: '/about',
  contact: '/contact',
  login: '/login',
  register: '/register',
  membership: '/membership',
  onboardingInitium: '/onboarding/initium',
  onboardingAscensio: '/onboarding/ascensio',
  onboardingDominus: '/onboarding/dominus',
  applicationPending: '/application-pending',
  appHome: '/app/home',
  dashboard: '/app/dashboard',
  courses: '/app/courses',
  feed: '/app/feed',
  forum: '/app/forum',
  profile: '/app/profile',
  dominusArea: '/app/dominus',
  adminDnApplications: '/app/admin/dn-applications',
}

