export const routes = {
  home: '/',
  appHome: '/dashboard',
  hem: '/hem',

  about: '/about',
  contact: '/contact',
  login: '/login',
  register: '/register',
  membership: '/membership',
  onboardingInitium: '/onboarding/initium',
  onboardingAscensio: '/onboarding/ascensio',
  onboardingDominus: '/onboarding/dominus',
  onboardingDominus2: '/onboarding/dominus2',
  applicationPending: '/application-pending',
  applicationPending2: '/application-pending-2',
  dashboard: '/dashboard',
  courses: '/courses',
  feed: '/feed',
  forum: '/forum',
  messages: '/messages',
  profile: '/profile',
  publicProfile: '/profile/:uid',
  publicShareProfile: '/public-profile/:uid',
  adminReviews: '/admin/reviews',
  adminDnApplications: '/admin/dn-applications',
  adminDnApplications2: '/admin/dn-applications-2',
  payment: '/payment',
  verify: '/verify',
  subscribe: '/subscribe',
  splash: '/splash',
  profileView: (uid: string) => `/profile/${uid}`,
  publicShareProfileView: (uid: string) => `/public-profile/${uid}`,
  messagesWith: (uid: string) => `/messages?with=${encodeURIComponent(uid)}`,
}

