export const routes = {
  home: '/',
  hem: '/hem',
  about: '/about',
  contact: '/contact',
  login: '/login',
  register: '/register',
  membership: '/membership',
  onboardingInitium: '/onboarding/initium',
  onboardingAscensio: '/onboarding/ascensio',
  onboardingDominus: '/onboarding/dominus',
  applicationPending: '/application-pending',
  dashboard: '/dashboard',
  courses: '/courses',
  feed: '/feed',
  forum: '/forum',
  profile: '/profile',
  adminReviews: '/admin/reviews',
  adminDnApplications: '/admin/dn-applications',
  payment: '/payment',
  verify: '/verify',
  subscribe: '/subscribe',
}

